name: Deploy App

on:
  push:
    branches: [ main ]

permissions:
  contents: read
  packages: write

jobs:

  build-and-push:
    runs-on: ubuntu-latest
    outputs:
      image_tag: ${{ steps.meta.outputs.tags }}
    steps:
      -
        name: Checkout code
        uses: actions/checkout@v3
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=sha
            latest
      -
        name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}

  deploy:
    environment: Production
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to VM via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

            docker pull ghcr.io/${{ github.repository }}:latest

            docker stop nest-app || true
            docker rm nest-app || true

            docker run -d \
              --name nest-app \
              --restart always \
              -p 3000:3000 \
              -e MONGODB_URI="${{ secrets.MONGODB_URI }}" \
              -e MONGODB_NAME="${{ vars.MONGODB_NAME }}" \
              -e AZURE_BLOB_STORAGE_CONNECTION_STRING="${{ secrets.AZURE_BLOB_STORAGE_CONNECTION_STRING }}" \
              -e JWT_SECRET_KEY="${{ secrets.JWT_SECRET_KEY }}" \
              -e JWT_EXPIRES_IN="${{ vars.JWT_EXPIRES_IN }}" \
              -e SMTP_USER="${{ secrets.SMTP_USER }}" \
              -e SMTP_HOST="${{ secrets.SMTP_HOST }}" \
              -e SMTP_PASSWORD="${{ secrets.SMTP_PASSWORD }}" \
              -e SMTP_PORT="${{ secrets.SMTP_PORT }}" \
              -e SSH_HOST="${{ secrets.SSH_HOST }}" \
              ghcr.io/${{ github.repository }}:latest
            
            docker image prune -af